---
- name: Download and install update
  hosts: all
  become: true
#  become_user: root

  tasks:
    - name: Add Ansible user to host
      ansible.builtin.user:
        name: ansible
        password: $5$zkIkSryqmw8dQuk9$UpXmi6XNxDKQeA9Rt2cMwiAOFdkcnXkbz2v36YAjIlD
        shell: /bin/bash
        groups: sudo
        append: true
    - name: Create SSH key
      ansible.builtin.user:
        name: ansible
        generate_ssh_key: true
        ssh_key_type: ed25519
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_ansible_ed25519
    - name: Add autorized key admin into *.pub keyfile
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '/home/smb/.ssh/smb_dmz151_ed25519.pub') }}"
    - name: Add autorized key ansible-user into *.pub keyfile
      # when: inventory_hostname not in {{ groups['managment_hosts'] }} # Так тоже работает но ругается
      when: inventory_hostname not in groups['managment_hosts']
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '/home/ansible/.ssh/id_ansible_ed25519.pub') }}"
    - name: Add autorized key ansible-user into *.pub keyfile
      when: inventory_hostname in groups['managment_hosts']
      ansible.posix.authorized_key:
        user: ansible
        state: absent
        key: "{{ lookup('file', '/home/ansible/.ssh/id_ansible_ed25519.pub') }}"
