---
- name: Download and install update
#  strategy: debug # При сбое в задании включается режим отладки
  hosts: all
  become: true
#  become_user: root
    # При создание соединения запускает  socks5h-прокси на удаленном сервере
    # в данном случае для доступа в интернет через SSH тунель
#   ansible_become_pass: 0000000000
#  environment:
#   http_proxy: "socks5h://127.0.0.1:3128" # Настраиваем параметры http-прокси
#   https_proxy: "socks5h://127.0.0.1:3128"
#   ftp_proxy: "socks5h://127.0.0.1:3128"
  tasks:
    - name: Packet update
      ansible.builtin.apt:
        update_cache: true # Выполняет операцию  'apt-get ubdate' на хосте
        cache_valid_time: 30 # Разрешает обновление кеша только если тот старше порогового значения '3600' во избежание ненужных затрат времени при отладке
        upgrade: dist
      environment:
        http_proxy: "socks5h://127.0.0.1:3128"  # Настраиваем параметры http-прокси
#      https_proxy: "socks5h://127.0.0.1:3128"
#      ftp_proxy: "socks5h://127.0.0.1:3128
    - name: Install qemu-guest-agent
      ansible.builtin.apt:
        name:
          - qemu-guest-agent
        state: present
      environment:
        http_proxy: "socks5h://127.0.0.1:3128"  # Настраиваем параметры http-прокси
    - name: Running qumu-guest-agent
      ansible.builtin.systemd:
        name: qemu-guest-agent
        enabled: true
        state: started
